name: ntpctl
version: '0.1'
summary: Simple snap to set an ntp server address
description: |
  Set a inetwork timeserver via cmdline or using a snap set variable
  with this snap.

grade: stable
confinement: strict
architectures: [ all ]

apps:
  ntpctl:
    command: ntpctl
    plugs: [ timeserver-control ]

parts:
  binary:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp ntpctl $SNAPCRAFT_PART_INSTALL/bin/
