name: ntpcontrol
version: '0.1'
summary: Simple snap to set an ntp server address
description: |
  Set a network timeserver via cmdline or using a snap set variable
  with this snap.
  .
  For more information see https://github.com/ogra1/ntpcontrol

grade: stable
confinement: strict
architectures: [ all ]

hooks:
  configure:
    plugs: [ timeserver-control, network-bind ]

apps:
  ntpcontrol:
    command: ntpcontrol
    plugs: [ timeserver-control ]

parts:
  binary:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp ntpcontrol $SNAPCRAFT_PART_INSTALL/bin/
